services:
    db:
        image: mariadb:lts
        restart: always
        environment:
            MARIADB_USER: "${MARIADB_USER}"
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        networks:
            - backend

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - backend

networks:
    backend:
        driver: bridge