name: "challenge-bravo-lucas"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8000:80
        volumes:
            - api-data:/data/api
        networks:
            - backend
        environment:
            MARIADB_USER: "${MARIADB_USER}"
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
            CURRENCY_API_KEY2: "${CURRENCY_API_KEY2}"
    db:
        image: mariadb:lts
        restart: always
        environment:
            MARIADB_USER: "${MARIADB_USER}"
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        networks:
            - backend

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - backend

volumes:
    api-data:

networks:
    backend:
        name: backend
        driver: bridge