name: "challenge-bravo-lucas"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: fastapi_currencyexchange_lucas
        restart: always
        ports:
            - 8000:8000
        volumes:
            - api-data:/data/api
        networks:
            - backend
        environment:
            EXPIRATION_TIME: "${EXPIRATION_TIME}"
            MARIADB_USER: "${MARIADB_USER}"
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
            CURRENCY_API_KEY2: "${CURRENCY_API_KEY2}"
        depends_on:
            - db
    db:
        image: mariadb:11.4
        restart: always
        environment:
            MARIADB_USER: "${MARIADB_USER}"
            MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        networks:
            - backend
        volumes:
          - mariadbdata:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - backend

volumes:
    api-data:
    mariadbdata:

networks:
    backend:
        name: backend
        driver: bridge